Repository selfxyz/self, pull requests merged in 2025-05, with the labels that each got.

#583 [BUG] fix undefined tracking event error
  app/src/components/buttons/AbstractButton.tsx
Labels: bug

#581 fix the ski prefix issue
  common/src/utils/certificate_parsing/utils.ts
  sdk/common/package.json
Labels: hotfix

#555 Feat/eu id contracts
  contracts/contracts/IdentityVerificationHubImplV2.sol
  contracts/contracts/constants/AttestationId.sol
  contracts/contracts/constants/CircuitConstantsV2.sol
  contracts/contracts/interfaces/IIdentityVerificationHubV2.sol
  contracts/contracts/libraries/Formatter.sol
  contracts/contracts/libraries/IdCardAttributeHandler.sol
  contracts/ignition/modules/deployIdCardRegistry.ts
  contracts/ignition/modules/deployIdCardVerifier.ts
  contracts/ignition/modules/deployV2.ts
  contracts/scripts/findErrorSignature.ts
  contracts/scripts/setVerifiersV2.ts
Labels: EU ID
